### ISSUE TITLE
error in your example .ipynb

### ISSUE THREAD

**Issue by spring-haru** [letsgoexploring/fredpy#1]
I tried to run your example [.ipynb file](https://www.briancjenkins.com/fredpy/docs/build/html/fredpy_examples.html), but an error occurred:

```
u = fp.series('UNRATE')

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-e73e0953d09e> in <module>
----> 1 u = fp.series('UNRATE')

~/anaconda3/envs/latest/lib/python3.8/site-packages/fredpy/__init__.py in __init__(self, series_id, observation_date)
    109 
    110             self.series_id = series_id
--> 111             self.title = results['seriess'][0]['title']
    112             self.frequency = results['seriess'][0]['frequency']
    113             self.frequency_short = results['seriess'][0]['frequency_short']

KeyError: 'seriess'
```

What am I missing here?

fredpy-3.2.0

**Comment by letsgoexploring** [comment]
Sorry for the late reply. Did you load your API key properly? The issue is
that no data is being downloaded.

Also, I made some changes to fredpy awhile ago and forgot to update the
documentation and examples. I have now done both.

Best regards,

Brian

**Comment by spring-haru** [comment]
It worked. Thanks (^_^)

BTW, your Computational Macro JN are great.  I will use `linearsolve` in my undergrad course. Great work!

**Comment by hajimebusuzima96** [comment]
jupyter lab just freeze at

**Comment by hajimebusuzima96** [comment]
jupyter lab just freeze at `import fredpy as fp`

**Comment by letsgoexploring** [comment]
I am sorry that you are having this issue. I just confirmed that I can
import and run fredpy in Jupyter Lab. Are you still having the problem?
Have you tried another Python environment to see if the issue is Jupyter
Lab or something deeper?
